apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
         app: myapp
    spec:
      containers:
        - name: myapp
          image: centos:latest
          command: ["sleep"]
          args: ["3600"]
          env:
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: mysql-credential
                key: username
          - name: MYSQL_PASSWD
            valueFrom:
              secretKeyRef:
                name: mysql-credential
                key: password
          - name: MYSQL_PORT
            valueFrom:
              secretKeyRef:
                name: mysql-credential
                key: port



