apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
         app: myapp
    spec:
      containers:
        - name: myapp
          image: centos:latest
          command: ["sleep"]
          args: ["3600"]
          volumeMounts:
            - name: myapp
              mountPath: /usr/loca/myapp/config/
      volumes:
        - name: myapp
          configMap:
            name: myapp

